### ISSUE TITLE
Sections and/or Areas on Gauge don't work anymore

### ISSUE THREAD

**Issue by countfloyd** [JFXtras/jfxtras-labs#10]
Not sure what the difference between sections and areas but specifying either one doesn't show up on the gauge. Sometimes it also causes NullPointerExceptions. Code sample:

```
        Section yellow = new Section(currentMaxMB * 0.8, currentMaxMB * 0.9, Color.YELLOW);
        Section red = new Section(currentMaxMB * 0.9, currentMaxMB, Color.RED);
        gauge.setAreasHighlighting(true);
        gauge.setAreasVisible(true);
        gauge.getAreas().add(yellow);
        gauge.getAreas().add(red);
```

**Comment by HanSolo** [comment]
Will take a look at it. Might be related to the modifications that have been made for fxml compatibility.

**Comment by HanSolo** [comment]
It seemed to be fixed but now I saw the NPE too...so reopen...

**Comment by HanSolo** [comment]
Ok, it works for me...here's my code (but your's work too)...

Radial gauge = new Radial();
Section[] areas = {
    new Section(gauge.getMaxValue() \* 0.8, gauge.getMaxValue() \* 0.9, Color.YELLOW),
    new Section(gauge.getMaxValue() \* 0.9, gauge.getMaxValue(), Color.RED)
};

Section[] sections = {
    new Section(gauge.getMaxValue() \* 0.2, gauge.getMaxValue() \* 0.3, Color.BLUE),
    new Section(gauge.getMaxValue() \* 0.3, gauge.getMaxValue() \* 0.4, Color.LIME)
};

gauge.getGaugeModel().setAreas(areas);
gauge.setAreasVisible(true);

gauge.getGaugeModel().setSections(sections);
gauge.setSectionsVisible(true);

**Comment by countfloyd** [comment]
I should have mentioned I'm using a 2.2 beta. Maybe that's why it's not working. I can't see any areas or sections working in 2.2.

**Comment by HanSolo** [comment]
Hmm, strange I'm on 2.2 b16 and everything looks fine...?

Cheers,

Gerrit Grunwald

Westfalenstraße 93
48165 Münster

Mail:      han.solo@muenster.de
Mobile: +49 (0)171 1745350
WWW:  http://harmonic-code.org

Am 12.07.2012 um 20:19 schrieb countfloyd reply@reply.github.com:

**Comment by countfloyd** [comment]
Here's how I create my gauges. Maybe that will help:

```
    return GaugeBuilder.create()
            .backgroundDesign(Gauge.BackgroundDesign.LIGHT_GRAY)
            .frameDesign(Gauge.FrameDesign.STEEL)
            .pointerType(Gauge.PointerType.TYPE2)
            .valueAnimationEnabled(true)
            .niceScaling(true)
            .glowOn(true)
            .gaugeType(GaugeBuilder.GaugeType.RADIAL_HALF_N)
            .areasVisible(true)
            .unit("MB")
            .animationDuration(1000)
            .minMeasuredValueVisible(true)
            .maxMeasuredValueVisible(true)
            .niceScaling(true)
            .thresholdVisible(false)
            .ledVisible(false)
            .build();
```

**Comment by countfloyd** [comment]
Sorry, I must be doing something wrong. I can't even get your code to work right. Also, if I call setAreaHighlighting(true), I still get NPE. Not sure what that call does.

I'm on a Mac using the latest git jfxtras-labs code as of now and jdk7u6 build 19 which includes JavaFX 2.2 b17. It used to work a few weeks ago. Not sure when it stopped working. Thanks for your help.
