### ISSUE TITLE
GridView DoubleProperties never get initialized

### ISSUE THREAD

**Issue by becast** [JFXtras/jfxtras-labs#109]
It seems that in the latest Versions of GridView the DoubleProperty of cellWidth, cellHeight, horizontalCellSpacing and verticalCellSpacing never get inizialized and are "null" so any .bind() operation or similar causes a NullPointerException

**Comment by tbee** [comment]
Looking at the history of the sources it seems that the contributor is not maintaining it anymore. This is one of the risks of using Labs; it's a playground with no warranty or support. I would advice to switch to another implementation, or -if you can't or it would be much more work- adopt the source and submit a patch.
