### ISSUE TITLE
Skinning issue with SimpleMetroArcGauge and BasicArcGauge

### ISSUE THREAD

**Issue by jbertoia** [JFXtras/jfxtras-labs#110]
I am truly impressed with these libraries, your work is outstanding!

In working with the SimpleMetroArcGauge I believe that there is an issue with the skinning of it and the BasicArcGauge.

When the minimum or maximum value is updated the ValuePane appears to be re-sized incorrectly and the css 'value-format' is also dropped or not rendered correctly.

![gaugeerror](https://cloud.githubusercontent.com/assets/12626452/7836292/2b9d5536-044d-11e5-9611-280d7cb8bce5.gif)

![gaugeerror2](https://cloud.githubusercontent.com/assets/12626452/7836527/ccaca5b6-044e-11e5-9f84-5fa51db775b6.gif)

Simply re-sizing the control and forcing it to re-render causes the ValuePane to be correctly re-sized and the 'value-format' css to be correctly implemented.  

Unfortunately my knowledge of css, skinning and how javafx uses it is very limited and I think I have about exhausted my  ability to further localize the problem.  Any insight into a short term workaround would be greatly appreciated.

jeff

**Comment by tbee** [comment]
Thanks for reporting. The issue involving the loss of value-format is something I already posted to the JavaFX developers; I do not believe the gauge is at fault there. This could also explain the scaling issue you describe. But as a result of changing the min/max is not what I am seeing in JFXtras samples. Can you extract a small application showing the problem?

**Comment by jbertoia** [comment]
The screenshots above were taken from JFXtras samples. I should have mentioned that.
If I am answering the wrong question just ask again sometimes I am dense.  ;)

Please see below....  Notice that the Maximum value is 101.

![smag](https://cloud.githubusercontent.com/assets/12626452/7837360/7ba8a8da-0454-11e5-9731-78cc436c2b03.gif)

Simply using the scroller to go down to 100 causes this.

![smag1](https://cloud.githubusercontent.com/assets/12626452/7837410/be6715d0-0454-11e5-9983-3a4b6e9ec033.gif)

I have tested it with:

```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by tbee** [comment]
Indeed! Why haven't I seen that sooner (I run the samples a lot). Uh. Strange. Thanks, I'll look into it.

**Comment by tbee** [comment]
An optimization was optimizing too hard

**Comment by tbee** [comment]
New version released.

**Comment by jbertoia** [comment]
Thanks Tom!

Both issues appear to be resolved.  Appreciate your fast support.
