### ISSUE TITLE
does BeanPathAdapter work?

### ISSUE THREAD

**Issue by PavelTurk** [JFXtras/jfxtras-labs#111]
I use for DTO POJOS. And for desktop client GUI I use JavaFX. And of course, I would like to have bidirectional (not mono!) data binding. I've found two solutions:

1) to use special classes Adapters. For example if we have POJO class Person, then we create JavaFx (*property) class PersonAdapter. Besides in POJO Person we add PropertyChangeSupport. This method works, however it's necessary for every DTO write DTOAdapter. - bad.

2)I've found this article https://ugate.wordpress.com/2012/06/14/javafx-programmatic-pojo-bindings/ and this code for javafx8 https://github.com/JFXtras/jfxtras-labs/blob/8.0/src/main/java/jfxtras/labs/scene/control/BeanPathAdapter.java . To tell the truth I didn't understand how you will find out if the POJO is changed. By other words if javafx changes - POJO changes it's clear. But if POJO changes? Some mystery I thought and desided to test

class Person{
 private String name;
 public void setName(String name){
 this.name=name;
 }
 public String getName(){
  return this.name;
  }
}

And the testing code:

Person person=new Person();
SimpleStringProperty sp=new SimpleStringProperty();
BeanPathAdapter<Person> testPA = new BeanPathAdapter<>(person);
testPA.bindBidirectional("name", sp);
person.setName("Name1");
System.out.println("Test1:"+sp.get());
sp.set("Name2");
System.out.println("Test2:"+test.getName()

Here is the result:

Test1:null
Test2:Name2

So we see that direction javafx property -> pojo works. However, pojo->javafx property doesn't. Or I do something wrong, or it doesn't work? Maybe someone will sugest a better solution?

**Comment by ronsmits** [comment]
A bit late but dont you need a propertyChangeListener for that?

**Comment by tbee** [comment]
closed because of no response
