### ISSUE TITLE
SimpleMetroArcGauge stays empty on android 5.1.1

### ISSUE THREAD

**Issue by rwijngaa** [JFXtras/jfxtras-labs#115]
I created a SimpleMetroArcGauge but this is shown blank on Android. It does however show on the desktop and IPhoneSimulator. I (retro lambda ) compiled  'org.jfxtras:jfxtras-gauge-linear:8.0-r5-SNAPSHOT' to get a Java 7 version that would work on Android.

i use  org.javafxports:jfxmobile-plugin:1.0.7 and 'org.jfxtras:jfxtras-controls:8.0-r5-SNAPSHOT'
'org.jfxtras:jfxtras-gauge-linear:8.0-r5-SNAPSHOT'

This are my android options:
    android {
        manifest = 'src/android/AndroidManifest.xml'
        dexOptions {
            javaMaxHeapSize = '2048m'
        }
    }

**Comment by tbee** [comment]
I'm currently trying to get my JFXtras/Android environment working again; but VMware and Windows10 are not playing along nicely anymore. VMWare is refusing the connect the Android tablet to the guest. So I cannot reproduce it ATM.

**Comment by jperedadnr** [comment]
Actually, a 'blank screen' could mean many things.

Run this on command line:

`adb logcat -v  threadtime`

and have a look at the console. You should find either an exception or a Sigsegv. If it is an exception, you will find an explanation for the issue.

If you don't find a solution, post here that output so we can help

**Comment by tbee** [comment]
I have just verified that the gauge works on my Nexus 7 (1st generation - Android 5.1.1). Even the animation is smooth. So it is not JFXtras nor Android that is causing your problems.

**Comment by tbee** [comment]
I have closed the issue, because it does not seem to be JFXtras related. You may still post more info, so we can help.

**Comment by tbee** [comment]
![screenshot_2016-01-23-07-32-57](https://cloud.githubusercontent.com/assets/1429698/12529020/9dac9c84-c1aa-11e5-9826-fc819a2cbbfe.png)

**Comment by rwijngaa** [comment]
Yes it works now!. Doing a "adb logcat -v threadtime" showed me that i had a typo in my
AndroidManifest.xml (main.class). Thanks for all the help though and sorry to have wasted your time
Regards
Rino
