### ISSUE TITLE
Error on extends abstract class

### ISSUE THREAD

**Issue by eldevanjr** [JFXtras/jfxtras-labs#117]
I try to use BeanPathAdappter with a class that contains one field, this Field is another class that extends one abstract class , new BeanPathAdapter<>(Lancamento).bindBidirectional("ipi.aliquota", getIpiAliquota().numberProperty(), BigDecimal.class);
Lancamento was a Class that contain Ipi.class and Ipi.class extends AbstractImposto.class, where is my fields .
if I put AbstractImposto.class fields inside Ipi.class and not extends, 'bindBidirectional' works, so binding with inheritance  doesn't work?
Thanks.

**Comment by tbee** [comment]
This is code in our play garden project, jfxtras-labs, and comes with no guarantee concerning quality or support. Given the age of this issue I have to assume the original contributor is no longer supporting it.
