### ISSUE TITLE
BigDecimal  access to textfield

### ISSUE THREAD

**Issue by georgemoralis** [JFXtras/jfxtras-labs#118]
It might be useful to have acess to textfield object for example if i want to make the textfield not editable and change the text to be centered right.

Also it might be useful to be able to have a method to hide the increase /decrease buttons (to make it a plain bigdecimal textfield)

**Comment by tbee** [comment]
This is code in our play garden project, jfxtras-labs, with no guarantee on quality or support. Given the age of this issue I have to assume that the original developer is no longer supporting it.
