### ISSUE TITLE
ResponsivePane

### ISSUE THREAD

**Issue by marckaraujo** [JFXtras/jfxtras-labs#119]
ResponsivePane isnt available anymore?

A blog talked about this: https://tbeernot.wordpress.com/2016/12/11/responsivepane/

**Comment by tbee** [comment]
Yes it is, it moved from labs to common. I'll update the blog.
https://github.com/JFXtras/jfxtras/blob/8.0/jfxtras-common/src/main/java/jfxtras/scene/layout/responsivepane/ResponsivePane.java
