### ISSUE TITLE
Help with BeanPathAdapter

### ISSUE THREAD

**Issue by lgLindstrom** [JFXtras/jfxtras-labs#121]
Hi.
Need some help here,,, :)

Two classes:
```
public class Class1() {
private string name;
private List<Class2> class2_List

// getters and setters goes here
}
```
```
public class Class2() {
private string name;
private string firstName;
private string lastName;

// getters and setters goes here
}
```

How do I use BeanPathAdapter adapter to make binding according to:

Class1.name should be displayed in a TextField
Class.1.class2_list should be displayed in a ListView with 3 columns,, one for name, firstName and lastName

Can anyone help here ??

**Comment by tbee** [comment]
This is code in our play garden project, jfxtras-labs, I'm not sure if the original developer still supports / maintains it.

**Comment by lgLindstrom** [comment]
Okay,,  
Better I try to connect to him directly then ??
