### ISSUE TITLE
BigDecimalField does not update text when the format is changed

### ISSUE THREAD

**Issue by rloschmann** [JFXtras/jfxtras-labs#130]
The text displayed by the BigDecimalField depends on the number (numberProperty()) and the format (formatProperty()).
When the number is changed the change is detected and the text is displayed according to the number and the format.
When the format is changed the change is not detected. The new format will be applied only on the next number change.

To solve this problem i propose to add the following block of code in BigDecimalFieldSkin.NumberTextField.initHandlers():

            // If format in controller changes update the TextField with the formatted number string
            CONTROL.formatProperty().addListener(new InvalidationListener() {
                @Override
                public void invalidated(Observable arg0) {
                    setText(CONTROL.getText());
                }
            });

**Comment by tbee** [comment]
Good idea, I've added it to the 11-r2-SNAPSHOT
