### ISSUE TITLE
JavaFx 8 support

### ISSUE THREAD

**Issue by Badisi** [JFXtras/jfxtras-labs#16]
In Java 8, com.sun.javafx.scene.control.skin.SkinBase is replaced by javafx.scene.control.SkinBase and component skin/behavior seems to have changed a little

Will JFXtras be ported to JavaFx 8 ?

Thanks

**Comment by tbee** [comment]
Yes.

**Comment by countfloyd** [comment]
Does the 8.0 branch actually work? Doesn't compile for me.

**Comment by HanSolo** [comment]
It compiles but not all controls are ported to JavaFX 8 at the moment but stay tuned...it will happen...
