### ISSUE TITLE
BeanPathAdapter is slow

### ISSUE THREAD

**Issue by jomoos** [JFXtras/jfxtras-labs#17]
I downloaded the latest zip file from master branch today. Then I ran the **BeanPathAdapterTrial1**. Now,when I select the person 1 from the demo, and then select a lot of items from hobby list, for example, first select 5th item(_'Hobby 5'_) from hobby list, then shift click 100th item, then the GUI goes non-responsive for 2-3 seconds. When I press the 'Remove selected hobbies' button, again the GUI goes non-responsive for 2-3 seconds.

**Comment by ugate** [comment]
Can you provide me with the Java version your running? Also, what is your
system configuration?

Not to say there couldn't be quite a bit more optimization done to the
adapter, but keep in mind that in the demo it's printing out 585 Hobby
fields for the TextArea "POJO Dump" (95 selections @ 3 fields/Hobby, 100
items @ 3 fields/Hobby). It's also calculating hash codes for each Hobby
instance. Not to mention all the other fields and their corresponding
visual overhead.

Can you try to comment out the "POJO Dump" code and see if that makes
a difference for you?

**Comment by jomoos** [comment]
Well, I have a Fedora 17 running on a Core i5 system with 2 GB of RAM. The Java version is:

```
$ java -version
java version "1.7.0_09-icedtea"
OpenJDK Runtime Environment (fedora-2.3.4.fc17-x86_64)
OpenJDK 64-Bit Server VM (build 23.2-b09, mixed mode)
```

I have commented out all three places where `dumpPojo` is called(actually I posted this issue after I tried this). It is still having the delay(a little less than earlier). Removing the hobbies have more delay than selecting them.

**Comment by ugate** [comment]
I'll look into ways that I can optimize this a bit further and let you know
what I come up with (suggestions/patches welcome :)

**Comment by ugate** [comment]
We may have to look into other means of optimization in future releases. However, binding "deep" POJO paths over a substantial number of beans isn't really practical in any sense. Typical applications usually limit the number of entries displayed in results (such as shown in the ensemble demo) and provide a means to paginate over remaining entries. The demo was originally intended to provide an example of the adapters capabilities and probably should not include so many bindings. I will update the demo so fewer bindings are used.
