### ISSUE TITLE
Problem with GroovyFX integration 

### ISSUE THREAD

**Issue by keilhofer** [JFXtras/jfxtras-labs#24]
Hi,
I have a problem integrating jfxtras into a groovyfx application.
I tried to add the calendarTextField to a gridpane, but I'm getting 
<code>org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'CalendarTextField[id=validFromField, styleClass=CalendarTextField]' with class 'jfxtras.labs.scene.control.CalendarTextField' to class 'javafx.scene.Node'
    at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:360)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:599)</code>
I don't understand why the CalenderTextField which is a Control cannot be cast to a Node (superclass).

Can anybody help me with this?

Thanks

**Comment by tbee** [comment]
Which JavaFX version are you using?

**Comment by keilhofer** [comment]
I'm using 2.2.7

**Comment by tbee** [comment]
Ok. CalendarTextField is a control and according to the Javadoc control extends Node.

https://github.com/JFXtras/jfxtras-labs/blob/2.2/src/main/java/jfxtras/labs/scene/control/CalendarTextField.java
http://docs.oracle.com/javafx/2/api/javafx/scene/control/Control.html

So this is interesting indeed. But I don't see how that class cast can occur.

Tom

**Comment by keilhofer** [comment]
Oahh, I got it... eclipse was cheating me. When I started the application with gradle I got a duplicate node exception. The problem with the groovy integration is, that creating a calendarfield in the gridpane immediately added it to the grid pane (although it is not visible, because I cannot set the row and column in the calendarfield constructor... whereas with the standard text fields of JavaFX one can set row and column of the gridpane in the constructor of the field e.g.
<code>nextCollectionField = textField(text:'', id:'nextCollectionField', disable: true, <b>row:rowNum, column: 1</b>)</code>). although row and column are attributes of the gridpane, not the textfield.
Using calendarField I cannot use the row and column attributes since GroovyFX is not aware of the calendarField somehow. What I did is 
<code>registerBeanFactory "calendarTextField", CalendarTextField</code>
but that seems to be not enough...<br>
The problem with the class cast is strange but solved, when I declare it outside of the (GroovyFX) gridpane parentheses. <br><bR>Did you ever try to integrate jfxtras controls into a GroovyFX application? It would be really nice to be able to use jfxtras in the "groovy way"... <br>Do you know a way to get the behavior as with the standard JavaFX textfield in GroovyFX for e.g. the CalendarTextField?
Thanks for your help!

**Comment by keilhofer** [comment]
forget it, it works... ECLIPSE shows an error, if I do this...
<code>validFromField = calendarTextField(dateFormat: STD_DATE_FORMAT, id:'validFromField', promptText: PROMPT_TEXT_DATE,row:rowNum, column: 1, columnSpan: 2)</code>
whereas it runs perfectly when I run it from gradle / command line....
<br>
Maybe I should order a IDEA license...
<bR>
Sorry for bothering you!! please close the issue...

**Comment by tbee** [comment]
Good to hear you got it working. I would love to improve JFXtras' controls in Groovy, but there are only so many hours in a day.

Tom
