### ISSUE TITLE
disabled Icon for calendarTextField ?

### ISSUE THREAD

**Issue by keilhofer** [JFXtras/jfxtras-labs#27]
Hi,
is it possible to add another icon for the disabled state of the calendarTextField (e.g. a grey icon instead of a nice colorful icon when the calendarTextField is enabled)?
This would be an enhancement.

A workaround is to just display a textfield and an image with the disabled icon.
But this has the drawback of having to style it the same way as the calendarTextField...
Thanks
Hans-Peter

**Comment by tbee** [comment]
A good suggestion, I'll take a look.

**Comment by tbee** [comment]
As far as I can see, the icon is already a color-less clock? (Just so we see the same thing.)

**Comment by keilhofer** [comment]
we changed the icon to a colorful one... but it is not possible to set an
icon for the disabled state... so far.

We would like to use the icons attached...
![CalendarTextFieldIconDisabled](https://f.cloud.github.com/assets/3225224/384617/1665a316-a65e-11e2-87ce-7adab920e85e.png)
![CalendarTextFieldIcon](https://f.cloud.github.com/assets/3225224/384618/17a24da6-a65e-11e2-98b0-5e66426b6547.png)

**Comment by tbee** [comment]
Ahhh, that explains. Ok. I'll pick that up.

**Comment by tbee** [comment]
Actually it turns out to be quite simple and already working. You normally would set the icon using something like:
     .CalendarTextField .icon {
         -fx-image: url("...");
     }

To set the disabled icon, you only need to add the pseudoclass:
     .CalendarTextField .icon:disabled {
         -fx-image: url("...");
     }

This CSS is not bad at all... ;-)

Tom

**Comment by keilhofer** [comment]
Oh.
I'm not so good in CSS... maybe I should get some training ... always
thought thats not for developers but for designers :-)

Thank you very much for your solution!
And also for the solution with the date formats. Its working very nicely
now!
