### ISSUE TITLE
list of parseFormats for CalendarTextField

### ISSUE THREAD

**Issue by keilhofer** [JFXtras/jfxtras-labs#28]
Hi,
another suggestion for enhancing the calendarTextField:
make it possible to set a list / string array of parse formats for parsing the typed in text.

This would enable the user to enter 010413 instead of 01.04.2013 if he wants to type in the date...
Maybe the dateFormat that is used for output should be added automatically to the list of possible input formats.
Thanks
Hans-Peter

**Comment by tbee** [comment]
Yes, I use a similar approach for my Swing calendar textfield.

**Comment by tbee** [comment]
Added date formats to the CalendarTextField.
