### ISSUE TITLE
Builders should have static create() method

### ISSUE THREAD

**Issue by countfloyd** [JFXtras/jfxtras-labs#3]
To be consistent with JavaFX, the Builder classes should have a static create method. Instead of:

new GaugeBuilder().create()...

it should be

GaugeBuilder.create()....

**Comment by HanSolo** [comment]
The static builders in JavaFX will be created automatically which is not possible in the JFXtras lib. There is a way of creating static builders by using enums but i'm not sure if this would be threadsafe. Therefore i won't add static builders to the classes at the moment (i will add them if i'm sure that they are threadsafe).
