### ISSUE TITLE
Broken CI - nobody cares?

### ISSUE THREAD

**Issue by gorskima** [JFXtras/jfxtras-labs#30]
Hi there, I recently received several emails about broken build, and indeed, last success has been registered '8 mo 16 days' ago. Is anyone taking care of the Jenkins located under http://jfxtras.com/jenkins/ ?

**Comment by HanSolo** [comment]
Stephen was responsible for the Jenkins server but he's simply to busy to take care of it anylonger. So if someone has the possibility to setup a build server feel free to take over. (Just my 0.02€)

**Comment by tbee** [comment]
Yes. Well. There currently is only one person able to access the Jenkins server, and he is not really spending time on the project. He did set me up with an account so I could pick it up, but I misplaced the password (the transfer was somewhat hectic).

The biggest problem is the fact that we moved to J7 / J8. The code itself is actually building (I  release builds every now and then). But I would love to have it release nightly builds.

We -the group- kinda settled to use Jenkins as the "commit confirmation". Maybe your mail will trigger him again.

Tom

**Comment by tbee** [comment]
Ah, I found that there is a second user for which I do have a password (that is what I misplaced). So I can configure Jenkins now, but now I need to be able to install J7 on the system, and then tell Jenkins to use it. Need SSH access I figure.

Tom

**Comment by gorskima** [comment]
It's green, good job :) Did you manage to install JDK 7 there?

**Comment by tbee** [comment]
<dancing on the desk>
Fixed it! I did. Yes yes. Yipperdidooda.
</dancing on the desk>

**Comment by tbee** [comment]
Yup. I'm a Jenkins noob, but google helped (as usual). Turns out Jenkins has an auto-download-and-install feature for the JDK, so no ssh needed. Unfortunately not for JDK8 yet.

**Comment by gorskima** [comment]
Ok, I guess the issue can be closed :)

**Comment by tbee** [comment]
Hey, don't say we from JFXtras aren't here to serve ;-)

**Comment by mkheck** [comment]
Rock on, Tom. Thanks for digging in and fixing!  :-D
