### ISSUE TITLE
CalendarTextField: parsing dates

### ISSUE THREAD

**Issue by keilhofer** [JFXtras/jfxtras-labs#47]
Hello,
the current CalendarTimeTextFieldCaspianSkin first looks at the dateFormat that is specified. If the parsing fails, it looks at the list of alternative formats specified.
I have a case where this is not optimal.
my dateFormat (which is also the OUTPUT format of the calendarTextField) is dd.MM.yyyy
I would like to parse "1.1.11" to "01.01.2011", but this is only possible, if the dd.MM.yy format is parsed before the dateFormat. (it turns to 01.01.0011 otherwise)
Is it possible to first parse the list of alternate formats and then the dateFormat? The user of the API can then put the standard date format at the position he likes (it's a list) and can therefore influence the parsing. At the moment this is not possible if the output format is a "long" format... but short formats should be parsed...
Thanks for any help!
Greetings 
Hans-Peter

**Comment by tbee** [comment]
Hm, your arguments make sense. Is there a situation where this is not wanted? You can always control the sequence...

It may break backwards compatibility, but since this is still in the labs project, that is allowed.

**Comment by tbee** [comment]
Moved the list before the default format. Pushed new snapshots.

Tom

**Comment by keilhofer** [comment]
Thank you!
