### ISSUE TITLE
com.sun.javafx.scene.control.skin.SkinBase not found in openjdk-8

### ISSUE THREAD

**Issue by walec51** [JFXtras/jfxtras-labs#49]
Wanted to test JFXtras-labs latest sources with JavaFX 8 but among other smaller compilation errors I can handle there is one BIG problem. The class com.sun.javafx.scene.control.skin.SkinBase used in all the JFXtras skin classes is not present in the latest build of JDK 8

**Comment by tbee** [comment]
Have you checked out the 8.0 branch?

**Comment by walec51** [comment]
Nope, my fault

**Comment by sounini** [comment]
please can anyone help with this problem
skinbase is not present in com.sun.javafx.scene.control.skin
i try to buil a carousel with javafx 8 following this code https://github.com/hjohn/Carousel
but the import of skinbase cannot be done
what should i do?

**Comment by frosch95** [comment]
You might give the javafx8 branch a try. https://github.com/hjohn/Carousel/tree/javafx8/Carousel
I haven't tried it on my own, but this seems the right branch to look at.
