### ISSUE TITLE
Can't create Gauge with any type other than RADIAL

### ISSUE THREAD

**Issue by countfloyd** [JFXtras/jfxtras-labs#5]
Using the GaugeBuilder, all gauges turn out with the RADIAL type no matter what you pass into the builder

Comment:
You should always set a gaugeType in the builder, otherwise it will default to Radial. Will take a closer look tomorrow. (Gerrit)

**Comment by countfloyd** [comment]
I think the problem is line 79 in GaugeBuilder

**Comment by HanSolo** [comment]
Okidoki, will take a closer look tomorrow it's under construction at the moment. Thx for the hint.

**Comment by HanSolo** [comment]
Ok, as far as I can see it on my phone I simply forget to check for the gaugeType in the builder. Will fix it tomorrow. Thx for the hint.
Cheers, Gerrit

**Comment by countfloyd** [comment]
No problem. Thanks a lot.

**Comment by countfloyd** [comment]
I'd like to reopen this because I still can't create any other gauge type with the GaugeBuilder. Seems to ignore it:

GaugeBuilder.create(GaugeBuilder.GaugeType.RADIAL_HALF_N)

ignores its argument.

**Comment by HanSolo** [comment]
Hmm, i checked it and ist worked so i'll check it again tomorrow. The following line should work:
Gauge gauge = GaugeBuilder.create().gaugeType(Gauge.GaugeType.RADIAL_HALF_N).create();

**Comment by HanSolo** [comment]
Ok, i checked it and you are right. I forgot to remove the GaugeType from the create() method. Will fix it.

**Comment by HanSolo** [comment]
Problem fixed in latest commit, now you could use it like this:
Gauge gauge = GaugeBuilder.create().gaugeType(GaugeBuilder.GaugeType.RADIAL_HALF_N).build();
