### ISSUE TITLE
LCD gauge layout/rendering issues

### ISSUE THREAD

**Issue by AmolHingmire** [JFXtras/jfxtras-labs#59]
Hi,

Greetings….

I have used the jfxtras labs (library) components in my project. Really nice work .
With the LCD gauge control I am facing following issues.

I bound the few of the properties of the LCD gauge.
//bind the properties.
        lcd.prefHeightProperty().bind(analogControl.heightProperty());
        lcd.prefWidthProperty().bind(analogControl.widthProperty());

```
    lcd.titleVisibleProperty().bind(analogControl.tagVisibleProperty());
    lcd.bargraphVisibleProperty().bind(analogControl.barGraphVisibleProperty());
    lcd.minMeasuredValueVisibleProperty().bind(analogControl.minValVisibleProperty());
    lcd.maxMeasuredValueVisibleProperty().bind(analogControl.maxValVisibleProperty());
    lcd.lcdDecimalsProperty().bind(analogControl.decimalNumberProperty()); 
```

Where the analogControl is my other control.

For titleVisibleProperty() it works fine.
However for rest of the properties it’s not working properly.
For example, for lcdDecimalsProperty() it does not show the changes  immediately . When I change the bargraphVisibleProperty() then only it shows the changed (latest) decimal values.
That is it does not renders the scene immediately or does not reflect the changes. Strange …!

For minMeasuredValueVisibleProperty() and maxMeasuredValueVisibleProperty() properties it does not show any changes.
For all these properties I tried to print the current values on the console using the changeListener() and I got the updated (latest) values on the console , however did not get the changes on the control.

Please do the needful.
For any concern please revert.

**Comment by tbee** [comment]
Closed because of inactivity
