### ISSUE TITLE
Radial gauge re sizing issue 

### ISSUE THREAD

**Issue by AmolHingmire** [JFXtras/jfxtras-labs#60]
Hi,

I am facing a very serious issue with re sizing Radial Gauge.
Please find the attached screen shots.
1) AT NORMAL SIZE
![radial](https://f.cloud.github.com/assets/5344315/1055347/21ae8c88-1134-11e3-81ae-e8e724c10429.PNG)

2) AFTER MAXIMIZE THE GAUGE SIZE
![radial_after_maximize](https://f.cloud.github.com/assets/5344315/1055348/31adf84e-1134-11e3-984e-421cb5241b12.PNG)

3) AFTER  MINIMIZE THE GAUGE SIZE
![radial_after_minimize](https://f.cloud.github.com/assets/5344315/1055349/35befd20-1134-11e3-9fd2-b0285838bd67.PNG)

**Comment by tbee** [comment]
Radial gauge is in labs and no longer supported. Please try BasicArgGauge, it will move to an official release once development is finished.
