### ISSUE TITLE
License need clarification/change

### ISSUE THREAD

**Issue by maslovalex** [JFXtras/jfxtras-labs#61]
jfxtras.org states

> JFXtras and JFXtras Labs are licensed under the BSD License

checking the code I found some files with "License" header and some without.

But the **most remarkable** thing is variety of headers. For example in https://github.com/JFXtras/jfxtras-labs/tree/2.2/src/main/java/jfxtras/labs/map
[Coorditane.java](https://github.com/JFXtras/jfxtras-labs/blob/2.2/src/main/java/jfxtras/labs/map/Coordinate.java) states 

> //License: GPL. Copyright 2009 by Stefan Zeller

but [MapPane.java](https://github.com/JFXtras/jfxtras-labs/blob/2.2/src/main/java/jfxtras/labs/map/MapPane.java) has LGPL header

[Timer](https://github.com/JFXtras/jfxtras-labs/blob/2.2/src/main/java/jfxtras/labs/animation/Timer.java) from https://github.com/JFXtras/jfxtras-labs/tree/2.2/src/main/java/jfxtras/labs/animation has "Modified BSD License"

I think you can find other examples.

That kind of situation already looks like License violation.
So, use of this project as dependency is questionable for any project.

**Comment by tbee** [comment]
You know, you are completely right. As coders we often do not pay much attention to the comment part on top of a file. And a lot of people contribute to JFXtras, so we should get the license headers straighten out.

**Comment by mario-s** [comment]
Those files without a license header in the map package are my own work completely. I just didn't pay much attention to it. However what can we do with the others that have a different license?

**Comment by tbee** [comment]
We need to go through them. This is the labs project, so probably nobody is paying much attention to it. But it should be set up correctly. We could also have the source files refer to the license on the website; less change of faults.

Tom

**Comment by mario-s** [comment]
That's a good suggestion: refer to the license on a website!

**Comment by maslovalex** [comment]
I don't know if gradle has anything like this : http://code.mycila.com/license-maven-plugin/

**Comment by miho** [comment]
The idea sounds good. But the root of the problem does still exist. People do not care about the header. If there was an LGPL header before it will still be there after the initial commit.

I would prefer an automatic solution (at least for Java code) that one could run via gradle, such as ./gradle repair-headers. A while ago I wrote such a library (based on antlr). The only requirement is that any Java file contains a valid package declaration. Files that don't contain one will be skipped. I just uploaded it to GitHub as independent library (was part of VRL before). You can find it here: [https://github.com/miho/VLiceneHeaderUtil](https://github.com/miho/VLiceneHeaderUtil)

Just drop me a line if you are interested.

**Comment by tbee** [comment]
Much better idea indeed! Interested :-)

Tom

**Comment by miho** [comment]
Cool! Will start writing a gradle plugin. Haven't done that before. So bear with me :)

Michael

**Comment by miho** [comment]
experimental repairHeaders task is now implemented. enable it by uncommenting the two lines that are commented:

```
apply {
    from 'gradle/mavenCentralDeploy.gradle'
    // from 'http://gradle-plugins.mihosoft.eu/latest/vlicenseheader.gradle'
}

// repairHeaders.licenseHeaderText = new File(projectDir,"license-template.txt")
```

Michael

**Comment by miho** [comment]
The repairHeaders task works well and should be able prevent license issues/outdated headers in the future.
