### ISSUE TITLE
Activation of travis-ci integration by a repo admin

### ISSUE THREAD

**Issue by McFoggy** [JFXtras/jfxtras-labs#66]
In order to finish travis-ci integration and thus benefit from the automatic builds (including Jemmy & JemmyFX tests), an admin must activate the hook between travis-ci and github. 
It might be either by:
- activating the on/off switch on https://travis-ci.org/JFXtras/jfxtras-labs
- or activating the hook from the settings page of the JFXtras github repository

**Comment by tbee** [comment]
Not sure what I need to do here.

**Comment by McFoggy** [comment]
When logged in travis-ci (using your github account), under your name choose accounts.

![travis-ci-javafx-1](https://f.cloud.github.com/assets/1119660/1230849/f842a48c-280e-11e3-935f-17b6da653e7f.png)

Then you should see the jfxtras srepositories. In my case you can see that I have no admin rights on them to activate travis-ci builds.

![travis-ci-javafx-2](https://f.cloud.github.com/assets/1119660/1230850/1d82c5e2-280f-11e3-8fac-b0921656347a.png)

If you have admin rights you should see switches to activate automatic builds for the jfxtras repossitories.
Here is an exemple with the repositories of my personnal account.

![travis-ci-javafx-3](https://f.cloud.github.com/assets/1119660/1230853/3ef286ea-280f-11e3-8b21-4176f5597dfa.png)

Hope an admin can finalize.

**Comment by tbee** [comment]
Finally found time to do this!
