### ISSUE TITLE
MonologFX classes

### ISSUE THREAD

**Issue by SirEdvin** [JFXtras/jfxtras-labs#73]
I see some problems in MonologFX classes:
1) In MonologFXButton class Localization and all string uses is too strange. For example copy from private field defLabels to private HashMap HashMap defaultLabels. Maybe, better to create static field with types, that loaded with Localication in static block?
2) Maybe, in MonologFXBuilder better to clone button in contructor?
3) With Localication, better to delete such string as  noBtn.setLabel("_No") in private void addOkButton, addNoYesButton.

Sorry my too bad English :(

**Comment by tbee** [comment]
Closed because of inactivity

**Comment by mkheck** [comment]
Hi Tom,

Not sure how I missed this one, I certainly didn't mean to ignore or
overlook it. :(  That said, with dialogs in JavaFX now, I'm not sure it
makes sense to push any big (i.e. non-bug-fixing) changes to MonologFX.
So...closing is probably the right action.

Again, apologies to all for somehow missing this.

Mark

**Comment by tbee** [comment]
NP. If you wait long enough all problems eventually will disappear :-)

**Comment by mkheck** [comment]
Hah! Well yes, but that certainly wasn't the intent here. (Looks away,
embarrassed...)
