### ISSUE TITLE
MonologFX Classes

### ISSUE THREAD

**Issue by SirEdvin** [JFXtras/jfxtras-labs#74]
I see some problems in MonologFX classes:
1) In MonologFXButton class Localization and all string uses is too strange. For example copy from private field defLabels to private HashMap HashMap defaultLabels. Maybe, better to create static field with types, that loaded with Localication in static block?
2) Maybe, in MonologFXBuilder better to clone button in contructor?
3) With Localication, better to delete such string as noBtn.setLabel("_No") in private void addOkButton, addNoYesButton.

Sorry my too bad English :(

**Comment by mkheck** [comment]
SirEdvin,

Funny you mention this...  :-)

Similar to Gerrit's statement yesterday, I've been planning to remove &
replace existing MonologFX functionality with something (hopefully much)
better. Thanks to your prompting, I'm going to make that my work/play
target for next weekend; I'll post an update on Nov 17th to the repo,
barring national or international disaster(s). :-D I've long been
dissatisfied with the current state of it and have been gathering ideas for
the reboot; thanks for adding your thoughts to the mix as well. I'm on it.

All the best,
Mark
