### ISSUE TITLE
adapt travis-ci build for branch handling

### ISSUE THREAD

**Issue by McFoggy** [JFXtras/jfxtras-labs#77]
- Not all branchs have a travis.yml build instruction file.
- Also it would be good if we could adapt our build file so that we can have badges for each branch (ie a build fail on branch 8.0 is not seen as a build fail in branch 2.2).

**Comment by tbee** [comment]
It should be fairly trivial to add the travis.yml to the other branch; we currently only have two, 2.2 and 8.0

What does that involve, "having badges"?

**Comment by McFoggy** [comment]
Yes it should.
Pushing a travis.yml version in the 8.0 branch might not be difficult.
What need a little bit more effort, or at least read some docs & exemples, is to find a way to distinguish branches in travis-ci. I have already seen things around this topic, so it just a matter of taking one hour to have a look. I'll do it next sunday.

The badges are the "icons" representing the build status in the readme.md on the project page.
There also if we could distinguish between branches it would be clean instead of having only the "latest" build result regardless the branch that fired the build.

**Comment by tbee** [comment]
In jenkins you can specify in the GIT plugin what branch it needs to checkout. The URL of course checks out the default 2.2 branch and that will change to 8.0 when J(FX)8 comes out.

**Comment by tbee** [comment]
Closed because of inactivity
