### ISSUE TITLE
Calender Text Field Tooltip 

### ISSUE THREAD

**Issue by rkarthi91** [JFXtras/jfxtras-labs#94]
Unable to get Tool tip to override the existing message "Type a date or use # for today, or +/-<number>[d|w|m|y] for delta's (for example: -3m for minus 3 months)\nUse cursor up and down plus optional shift (week), ctrl (month) or alt (year) for quick keyboard changes."   

Please provide a solution to override the calender tooltip message asap.

Thank you.

**Comment by tbee** [comment]
Right now we're in the process of extracting a formal JFXtras release from JFXtras-labs. I will pick this up as soon as that is done.

**Comment by rkarthi91** [comment]
Ok , and i am waiting for your next release .
And need more utilities for table view with Advanced features in next release 

Thank for your time bro ..

Regards  Karthick R Software EngineerSmart Seven Technologies .

Date: Thu, 20 Feb 2014 02:27:12 -0800

**Comment by tbee** [comment]
Is already fixed
