### ISSUE TITLE
BigDecimalField

### ISSUE THREAD

**Issue by tbee** [JFXtras/jfxtras-labs#98]
If I click-and-hold on the arrow DOWN button, the value start automatically changing, but it is incrementing, not decrementing.

**Comment by teabeeoh** [comment]
Hi Tom,

thanks for the report, I mixed up button handlers. It is fixed now.

Cheers

Thomas

Am 20.05.2014 um 19:58 schrieb Tom Eugelink notifications@github.com:

**Comment by tbee** [comment]
Thanks for the fix! I have found that writing a few tests uncovers exactly these kinds of slips.

**Comment by teabeeoh** [comment]
Hi Tom,

I was just checking my TestFX Test again, besides the fact, that my 
arrow buttons are not public accessible, is it possible to simulate a 
pressing and holding a mouse button with TestFX? I did not find out how 
at least...

Cheers

Thomas

Am 22.05.2014 16:47, schrieb Tom Eugelink:

**Comment by teabeeoh** [comment]
And one more thing. I was thinking to move BigDecimalField from 
jfxtras-lab to jfxtras, would that be ok? If yes what needs to be done, 
just moving the code from one project to the other?

Am 22.05.2014 16:47, schrieb Tom Eugelink:

**Comment by tbee** [comment]
Good question, that reminds me that I have no click-and-hold test on my ListSpinner either. TestFX has primitive methods like "press" and "release" which are used by "click". Maybe that will work. I need to try that also.

Tom

**Comment by tbee** [comment]
Basically yes, but code in JFXtras should try to have:
- an example in de samples application
- some testing to prevent regression

Now, I'm not totally 100% covered there either, because agenda does not have a test. But the rest is pretty close. It is just to get and keep the quality of JFXtras up to par.

Tom

**Comment by tbee** [comment]
Yes, that works fine.
move("<some css expression>");
press(MouseButton.PRIMARY);
TestUtil.sleep(1000);
release(MouseButton.PRIMARY);

**Comment by tbee** [comment]
Wrote and committed a press-and-hold test in ListSpinnerArrowTest

**Comment by teabeeoh** [comment]
Hmmh, thanks for the hint, but I keep getting unpredictable
[TestFX] User mouse movement detected. Aborting test.
log messages when I try to do the same.
I am using a move(bigDecimalField) moveBy(...,...) combination to get to 
the arrow buttons, but that should not be the problem as visually 
everything looks fine.

Am 26.05.2014 21:39, schrieb Tom Eugelink:

**Comment by tbee** [comment]
Closed because of inactivity

**Comment by afhussainwork** [comment]
Can you please unsubscribe me from this list?

**Comment by tbee** [comment]
No, that is something you have to do yourself. I cannot manage someone elses subscriptions.

**Comment by afhussainwork** [comment]
Do you know how to do that? There is no link here and I continually get spammed

**Comment by tbee** [comment]
GitHub has ways to unsubscribe from issues and repositories, but the UI sometimes is not very clear I agree. Google and you will find.

**Comment by afhussainwork** [comment]
Thanks
